name: aura_glide
description: "AuraGlide - The Calming Puzzle Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.9

  # Local Storage
  shared_preferences: ^2.2.2

  # UI/Animations
  google_fonts: ^6.1.0

  # Utilities
  equatable: ^2.0.5
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true